apiVersion: v1
kind: Service
metadata:
  name: giropops-senhas
  labels:
    app: giropops-senhas
spec:
  selector:
    app: giropops-senhas
  ports:
    - protocol: TCP
      port: {{ .Values.giropops-senhas.service.port }}
      nodePort: {{ .Values.giropops-senhas.service.NodePort }}
      targetPort: {{ .Values.giropops-senhas.service.targetPort }}
      name: {{ .Values.giropops-senhas.service.name }}
  type: {{ .Values.giropops-senhas.service.type }}